"""
Journal export tool.

Exports conversation sessions to markdown format for user download.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional


def format_journal_entry(
    user_message: str,
    assistant_response: str,
    timestamp: Optional[datetime] = None,
    skill: Optional[str] = None,
) -> str:
    """Format a single exchange as a journal entry.

    Args:
        user_message: User's message.
        assistant_response: Counselor's response.
        timestamp: When the exchange occurred.
        skill: Detected skill/topic.

    Returns:
        Formatted markdown string.
    """
    ts = timestamp or datetime.now(timezone.utc)
    time_str = ts.strftime("%H:%M")

    lines = [f"### {time_str}"]

    if skill and skill != "general-support":
        lines.append(f"*Topic: {skill.replace('-', ' ').title()}*")
        lines.append("")

    lines.extend([
        "**You:**",
        f"> {user_message}",
        "",
        "**Counselor:**",
        assistant_response,
        "",
        "---",
        "",
    ])

    return "\n".join(lines)


def export_session(
    user_id: int,
    history: list[tuple[str, str]],
    session_date: Optional[datetime] = None,
    include_summary: bool = True,
) -> str:
    """Export a full conversation session to markdown.

    Args:
        user_id: User identifier.
        history: List of (user_message, assistant_response) tuples.
        session_date: Date of the session.
        include_summary: Whether to include a reflection prompt.

    Returns:
        Complete markdown document.
    """
    date = session_date or datetime.now(timezone.utc)
    date_str = date.strftime("%Y-%m-%d")

    lines = [
        f"# Session Journal - {date_str}",
        "",
        f"*Session ID: {user_id}*",
        f"*Exported: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*",
        "",
        "---",
        "",
    ]

    if not history:
        lines.append("*No conversation history in this session.*")
    else:
        lines.append(f"## Conversation ({len(history)} exchanges)")
        lines.append("")

        for user_msg, assistant_msg in history:
            entry = format_journal_entry(user_msg, assistant_msg)
            lines.append(entry)

    if include_summary and history:
        lines.extend([
            "## Reflection",
            "",
            "Take a moment to reflect on this conversation:",
            "",
            "- What feelings came up for you?",
            "- What insights did you gain?",
            "- What's one thing you might try before our next conversation?",
            "",
            "*This journal is private. You can add your own notes below.*",
            "",
            "---",
            "",
            "### My Notes",
            "",
            "",
            "",
        ])

    # Footer
    lines.extend([
        "---",
        "",
        "*This journal was generated by your mental health counseling assistant. "
        "It is for personal reflection only and is not a clinical record.*",
    ])

    return "\n".join(lines)


def export_to_file(
    user_id: int,
    history: list[tuple[str, str]],
    output_path: str,
    session_date: Optional[datetime] = None,
) -> str:
    """Export session to a file.

    Args:
        user_id: User identifier.
        history: Conversation history.
        output_path: Path to write the file.
        session_date: Date of the session.

    Returns:
        Path to the created file.
    """
    content = export_session(user_id, history, session_date)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    return output_path
